### ISSUE TITLE
希望能曲线能支持(空)null数据

### ISSUE THREAD

**Issue by nightrainljh** [xcltapestry/XCL-Charts#7]
作者大哥，能否考虑曲线图能传人null数据，即数据是null时不绘制该点！

**Comment by xcltapestry** [comment]
传null? 中间数据源有断开？那你分成两个数据源传。

**Comment by nightrainljh** [comment]
奥，可以这么玩呀，谢谢！

在 2015-04-06 13:21:59，"XiongChuanLiang" <notifications@github.com> 写道：


传null? 中间数据源有断开？那你分成两个数据源传。

**Comment by wdt** [comment]
但是这么玩可以用相同颜色不？图例也需要同一个的话是不是不方便啦。记得以前teechart支持这种。我也建议支持
2015-5-13 下午12:03于 "nightrain" <notifications@github.com>写道：

**Comment by nightrainljh** [comment]
情况是这样的，好比我要展示光伏逆变器这一天的发电功率，从0点到24点的，5分钟采集一个点存库，然后从库里取出来展示成一条曲线，也就是从0分到1440分。各种原因导致，有些分钟没存上值，即中间有断开的，展示的时候这些点不需绘制！
我用的LineChart，lable集合我传的00:00, 00:05.....23:55,00:00；数据集合我把288个点数据放入LineData了，空值我暂时都放入0。
您说的分两个数据源，就是用两个LineData吗？ 那这样图表上方的图列也就成了两了；还有这两个数据源linedata，如何让第一段从00:00分绘制到12:00结束，第二段从13:05分开始绘制(好比12:00到13:05这期间没存数) 。如果中间断开了10次，那就得当10条曲线处理了。

**Comment by nightrainljh** [comment]
后来！我修改了linechart源码，修改下renderLine,支持数据集传null值绘制曲线

/**
		 * 绘制线
		 * @param canvas	画布
		 * @param bd		数据类
		 * @param type		处理类型
		 */
		private boolean renderLine(Canvas canvas, LineData bd,String type,int dataID)
		{
			if(null == categoryAxis || null == dataAxis) return false;
			
			if(null == bd)
			{
				Log.e(TAG,"传入的线的数据序列参数为空.");
				return false;
			}
			
			float initX =  plotArea.getLeft();
            float initY =  plotArea.getBottom();             
			float lineStartX = initX,lineStartY = initY;         
            float lineStopX = 0.0f,lineStopY = 0.0f;        
            													
			//得到分类轴数据集
			List<String> dataSet =  categoryAxis.getDataSet();
			if(null == dataSet ||dataSet.size() == 0){
				Log.e(TAG,"分类轴数据为空.");
				return false;
			}		
			//数据序列
			List<Double> chartValues = bd.getLinePoint();
			if(null == chartValues ||chartValues.size() == 0 )
			{
				Log.e(TAG,"当前分类的线数据序列值为空.");
				return false;
			}
				
			//步长
			float axisScreenHeight = getPlotScreenHeight();
			float axisDataHeight = (float) dataAxis.getAxisRange();	
			float XSteps = 0.0f;	
			int j = 0,childID = 0;	
			int tickCount = dataSet.size();		
			if( 0 == tickCount)
			{
				Log.e(TAG,"分类轴数据源为0!");
				return false;
			}else if (1 == tickCount)  //label仅一个时右移
			{
				j = 1;
			}			
			int labeltickCount = getCategoryAxisCount();
			XSteps = getVerticalXSteps(labeltickCount);
			
			
			float itemAngle = bd.getItemLabelRotateAngle();
			
			Double lastValue = null;		//当前点的前一个点值，初始为空
					
		    //画线
			for(Double bv : chartValues)
            {	
				if(0 == j)
            	{
            		lineStartX = lineStopX;
            		lineStartY = lineStopY;
            	}
				
				if (bv == null || bv.toString().equals("null"))	//当前点空值 
				{
					//lastValue不为空或为空都不绘制
				}
				else 											//当前点不为空
				{
					//参数值与最大值的比例  照搬到 y轴高度与矩形高度的比例上来 	                                             	
	            	float vaxlen = (float) MathHelper.getInstance().sub(bv, dataAxis.getAxisMin());				
					float fvper = div( vaxlen,axisDataHeight );
					float valuePostion = mul(axisScreenHeight, fvper);			    
	            
					
					//前一个相邻点为空，不绘制，只赋值lineStartX，lineStopX，lineStartY，lineStopY;
					if (lastValue == null || lastValue.toString().equals("null"))	
					{
		            	lineStopX = add(initX , j * XSteps);        	
		            	lineStopY = sub(initY , valuePostion);  

		            	lineStartX = lineStopX;
						lineStartY = lineStopY;
					}
					else //前一个相邻点为不为空，绘制
					{
						lineStopX = add(initX , j * XSteps);        	
		            	lineStopY = sub(initY , valuePostion);  
	   	
		            	if( getLineAxisIntersectVisible() == false &&
		            			Double.compare(bv, dataAxis.getAxisMin()) == 0 )
		            	{
		            		//如果值与最小值相等，即到了轴上，则忽略掉  
		            		lineStartX = lineStopX;
		    				lineStartY = lineStopY;
		            	}else
		            	{
			            	PlotLine pLine = bd.getPlotLine();           
			            	if(type.equalsIgnoreCase("LINE"))
			            	{
			            		
			            		if(getLineAxisIntersectVisible() == true ||
			            					Float.compare(lineStartY, initY) != 0 )	
			            		{	            		
			            			DrawHelper.getInstance().drawLine(bd.getLineStyle(), 
			            					lineStartX ,lineStartY ,lineStopX ,lineStopY,
			            					canvas,pLine.getLinePaint());		            			
			            		}
			            	}else if(type.equalsIgnoreCase("DOT2LABEL")){
			            		
			            		if(!pLine.getDotStyle().equals(XEnum.DotStyle.HIDE))
			                	{                		       	
			                		PlotDot pDot = pLine.getPlotDot();	        
			                		float radius = pDot.getDotRadius();
			                		float rendEndX  = lineStopX  + radius;  
			                		
			                		PlotDotRender.getInstance().renderDot(canvas,pDot,
			                				lineStartX ,lineStartY ,
			                				lineStopX ,lineStopY,
			                				pLine.getDotPaint()); //标识图形            		
			                			                		
			                		savePointRecord(dataID,childID, lineStopX  + mMoveX, lineStopY  + mMoveY,
			                				lineStopX - radius + mMoveX,lineStopY - radius + mMoveY,
			                				lineStopX + radius + mMoveX,lineStopY + radius + mMoveY);
			                		
			                		childID++;
			                		
			            			lineStopX = rendEndX;	            			
			                	}
			            		
			            		if(bd.getLabelVisible()) //标签
			                	{	                	            			
			            			DrawHelper.getInstance().drawRotateText(this.getFormatterItemLabel(bv), 
			    										lineStopX, lineStopY, itemAngle, 
			    										canvas, pLine.getDotLabelPaint());
			                	}
			            			            		
			            	}else{
			            		Log.e(TAG,"未知的参数标识。"); //我不认识你，我不认识你。
			            		return false;
			            	}      				
		            	
							lineStartX = lineStopX;
							lineStartY = lineStopY;
		            	}
					}
				}

				lastValue = bv;
            	j++;
            }
			
			return true;
		}

**Comment by xcltapestry** [comment]
刚看到信息，“各种原因导致，有些分钟没存上值，即中间有断开的，展示的时候这些点不需绘制！”原来是这种情况，那你是选错图了.你不应当用linechart而应当是用splinechart即可达到需求.  哈哈   不过你最后改源码达到效果也成.

**Comment by nightrainljh** [comment]
奥，哈哈，没仔细看您源码，项目需求，在网上看到了，就用您的做项目了！有时间再好好看看源码，图表架构挺好，值得学习！

**Comment by xcltapestry** [comment]
线图的变种很多，所以在图库中有分折线图和曲线图两种线图类型，你这种适合曲线图，当时多看下例子就不会这么累了。  关了。
